# This service is used to get the pose of the model described by the given id
string id
---
# Pose in UE4 world coordinates with ROS conventions
geometry_msgs/Pose pose
# true if model could be found
bool success
