# This service is used to delete the model described in
# the instance_id from the unreal world.
unreal_world_control_msgs/InstanceId instance_id
---
# true if model was deleted successfully.
bool success
