# Models that should be highlighted
unreal_world_control_msgs/InstanceId[] instance_ids
# True - if given models are supposed to be highlighted.
# Flase - if the highlighting should be removed.
bool to_be_highlighted
# 1-5 for different colors.
int color_index
---
# True if ALL models were successfully highlighted
bool success
